name: Pokemanager Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=." >> $GITHUB_ENV

      - name: Run tests
        run: uv run pytest